### ISSUE TITLE
Private key in public repo????

### ISSUE THREAD

**Issue by andrewgdotcom** [sirensolutions/chembl#1]
In branch `mp`:
![private-key](https://user-images.githubusercontent.com/617742/36609668-9288136e-18c5-11e8-923f-24c8fd14c922.png)

**Comment by emepyc** [comment]
They were included in the latest update from Andrea. I have now removed them from all the branches containing them.

**Comment by apierleoni** [comment]
for the record those where self signed keys, to be used just for dev work.
